# https://docs.render.com/deploy-hooks#using-with-github-actions

on:
  pull_request:
  push:
    branches: [shub]
    paths: ['client/**']

jobs:
  client-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Client
        env:
          deploy_url: 'https://api.render.com/deploy/srv-csmdt4dumphs73cn56fg?key=hQM9SmtDO08'
        run: |
          curl "$deploy_url"
